export const searchActionTypes = {
	FETCH_SEARCH_RESULTS_START: "FETCH_SEARCH_RESULTS_START",
	FETCH_SEARCH_RESULTS_SUCCESS: "FETCH_SEARCH_RESULTS_SUCCESS",
	FETCH_SEARCH_RESULTS_FAILURE: "FETCH_SEARCH_RESULTS_FAILURE",
};
