export const moviesActionTypes = {
	FETCH_POPULAR_MOVIES_START: "FETCH_POPULAR_MOVIES_START",
	FETCH_POPULAR_MOVIES_SUCCESS: "FETCH_POPULAR_MOVIES_SUCCESS",
	FETCH_POPULAR_MOVIES_FAILURE: "FETCH_POPULAR_MOVIES_FAILURE",
	INCREMENT_POPULAR_MOVIES_FETCH_PAGE: "INCREMENT_POPULAR_MOVIES_FETCH_PAGE",
	FETCH_MORE_POPULAR_MOVIES_START: "FETCH_MORE_POPULAR_MOVIES_START",
};
