export const moviesActionTypes = {
	FETCH_MOVIES_START: "FETCH_MOVIES_START",
	FETCH_MOVIES_SUCCESS: "FETCH_MOVIES_SUCCESS",
	FETCH_MOVIES_FAILURE: "FETCH_MOVIES_FAILURE",
	INCREMENT_CURRENT_MOVIES_FETCH_PAGE: "INCREMENT_CURRENT_MOVIES_FETCH_PAGE",
	FETCH_MORE_MOVIES_START: "FETCH_MORE_MOVIES_START",
	CHANGE_MOVIES_FETCH_TYPE: "CHANGE_MOVIES_FETCH_TYPE",
};
