export const tvShowsActionTypes = {
	FETCH_TV_SHOWS_START: "FETCH_TV_SHOWS_START",
	FETCH_TV_SHOWS_SUCCESS: "FETCH_TV_SHOWS_SUCCESS",
	FETCH_TV_SHOWS_FAILURE: "FETCH_TV_SHOWS_FAILURE",
	INCREMENT_CURRENT_TV_SHOWS_FETCH_PAGE:
		"INCREMENT_CURRENT_TV_SHOWS_FETCH_PAGE",
	FETCH_MORE_TV_SHOWS_START: "FETCH_MORE_TV_SHOWS_START",
	CHANGE_TV_SHOWS_FETCH_TYPE: "CHANGE_TV_SHOWS_FETCH_TYPE",
};
