export const tvShowsActionTypes = {
	FETCH_POPULAR_TV_SHOWS_START: "FETCH_POPULAR_TV_SHOWS_START",
	FETCH_POPULAR_TV_SHOWS_SUCCESS: "FETCH_POPULAR_TV_SHOWS_SUCCESS",
	FETCH_POPULAR_TV_SHOWS_FAILURE: "FETCH_POPULAR_TV_SHOWS_FAILURE",
	INCREMENT_POPULAR_TV_SHOWS_FETCH_PAGE:
		"INCREMENT_POPULAR_TV_SHOWS_FETCH_PAGE",
	FETCH_MORE_POPULAR_TV_SHOWS_START: "FETCH_MORE_POPULAR_TV_SHOWS_START",
};
