export const detailsActionTypes = {
	FETCH_MAIN_DETAILS_START: "FETCH_MAIN_DETAILS_START",
	FETCH_MAIN_DETAILS_SUCCESS: "FETCH_MAIN_DETAILS_SUCCESS",
	FETCH_MAIN_DETAILS_FAILURE: "FETCH_MAIN_DETAILS_FAILURE",
	FETCH_SIMILAR_START: "FETCH_SIMILAR_START",
	FETCH_SIMILAR_SUCCESS: "FETCH_SIMILAR_SUCCESS",
	FETCH_MORE_SIMILAR_START: "FETCH_MORE_SIMILAR_START",
	FETCH_SIMILAR_FAILURE: "FETCH_SIMILAR_FAILURE",
	INCREMENT_SIMILAR_FETCH_PAGE: "INCREMENT_SIMILAR_FETCH_PAGE",
	RESET_SIMILAR_FETCH_PAGE: "RESET_SIMILAR_FETCH_PAGE",
	FETCH_CAST_AND_CREW_START: "FETCH_CAST_AND_CREW_START",
	FETCH_CAST_AND_CREW_SUCCESS: "FETCH_CAST_AND_CREW_SUCCESS",
	FETCH_CAST_AND_CREW_FAILURE: "FETCH_CAST_AND_CREW_FAILURE",
};
