export const detailsActionTypes = {
	FETCH_MAIN_DETAILS_START: "FETCH_MAIN_DETAILS_START",
	FETCH_MAIN_DETAILS_SUCCESS: "FETCH_MAIN_DETAILS_SUCCESS",
	FETCH_MAIN_DETAILS_FAILURE: "FETCH_MAIN_DETAILS_FAILURE",
	FETCH_SIMILAR_START: "FETCH_SIMILAR_START",
	FETCH_SIMILAR_SUCCESS: "FETCH_SIMILAR_SUCCESS",
	FETCH_SIMILAR_FAILURE: "FETCH_SIMILAR_FAILURE",
};
